package main

import (
	"crypto/sha1"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/skip2/go-qrcode"
	"gopkg.in/yaml.v3"
)

type frontMatter struct {
	Events []event `yaml:"events"`
}

type event struct {
	Title        string   `yaml:"title"`
	Date         string   `yaml:"date"`
	URL          string   `yaml:"url"`
	Route        string   `yaml:"route"`
	Start        string   `yaml:"start"`
	End          string   `yaml:"end"`
	StartAddress string   `yaml:"start_address"`
	Tags         []string `yaml:"tags"`
}

type tmplEvent struct {
	Title    string   `json:"title"`
	Date     string   `json:"date"`
	Weekday  string   `json:"weekday"`
	Day      string   `json:"day"`
	Month    string   `json:"month"`
	URL      string   `json:"url"`
	Route    string   `json:"route"`
	Location string   `json:"location"`
	Address  string   `json:"address"`
	Tags     []string `json:"tags"`
	QR       string   `json:"qr"`
	Section  string   `json:"section"`
}

type tmplData struct {
	Generated string      `json:"generated"`
	SiteURL   string      `json:"site_url"`
	SiteQR    string      `json:"site_qr"`
	LogoPath  string      `json:"logo_path"`
	Events    []tmplEvent `json:"events"`
}

const typstTemplate = `// Auto-generated by cmd/buildpdf — do not edit.
#let accent       = rgb("#16a34a")
#let accent-soft  = rgb("#dcfce7")
#let accent-line  = rgb("#86efac")
#let ink          = rgb("#111827")
#let ink-soft     = rgb("#374151")
#let muted        = rgb("#6b7280")
#let card-bg      = rgb("#f9fafb")
#let card-border  = rgb("#e5e7eb")
#let chip-bg      = rgb("#ecfdf5")
#let chip-ink     = rgb("#047857")
#let link-ink     = rgb("#1d4ed8")

#let data = json("events.json")

#set document(
  title: "Ride Westside — Upcoming Rides",
  author: "Ride Westside",
)

#set page(
  paper: "us-letter",
  margin: (left: 14mm, right: 14mm, top: 22mm, bottom: 14mm),
  header: [
    #set text(font: "DejaVu Sans", size: 10pt, fill: ink)
    #grid(
      columns: (1fr, auto),
      align: (left + horizon, right + horizon),
      column-gutter: 8pt,
      [
        #text(size: 16pt, weight: "bold", fill: accent)[Ride Westside]
        #h(6pt)
        #text(size: 8.5pt, fill: muted)[Portland westside cycling community]
        #linebreak()
        #text(size: 8pt, fill: muted)[#link("https://ridewestside.org")[ridewestside.org]]
      ],
      image("site_qr.png", width: 14mm),
    )
    #v(-3pt)
    #line(length: 100%, stroke: 0.6pt + accent-line)
  ],
  footer: [
    #set text(font: "DejaVu Sans", size: 8pt, fill: muted)
    #line(length: 100%, stroke: 0.3pt + card-border)
    #v(3pt)
    #grid(
      columns: (1fr, 1fr, 1fr),
      align: (left, center, right),
      [ridewestside.org],
      [Page #context counter(page).display("1 of 1", both: true)],
      [Generated #data.generated],
    )
  ],
)

#set text(font: "DejaVu Sans", size: 9.5pt, fill: ink)
#set par(leading: 0.55em, justify: false)
#show link: it => text(fill: link-ink)[#it]

// ---------- Components ----------

#let chip(label) = box(
  fill: chip-bg,
  stroke: 0.3pt + accent-line,
  inset: (x: 5pt, y: 1.5pt),
  outset: (y: 1pt),
  radius: 2.5pt,
  text(size: 7.5pt, weight: "medium", fill: chip-ink)[#label],
)

#let date-badge(month, day, weekday) = box(
  fill: white,
  stroke: 0.6pt + accent,
  radius: 4pt,
  width: 16mm,
  inset: (x: 0pt, y: 4pt),
  align(center)[
    #text(size: 7.5pt, weight: "bold", fill: accent, tracking: 0.6pt)[#upper(month)]
    #v(-4pt)
    #text(size: 18pt, weight: "bold", fill: ink)[#day]
    #v(-4pt)
    #text(size: 7pt, fill: muted)[#upper(weekday)]
  ],
)

#let event-card(evt) = block(
  breakable: false,
  fill: card-bg,
  stroke: 0.5pt + card-border,
  radius: 4pt,
  inset: (x: 9pt, y: 8pt),
  width: 100%,
  below: 6pt,
  grid(
    columns: (auto, 1fr, auto),
    column-gutter: 10pt,
    align: (left + top, left + top, center + horizon),
    date-badge(evt.month, evt.day, evt.weekday),
    [
      #text(size: 11.5pt, weight: "bold", fill: ink)[#evt.title]
      #linebreak()
      #text(size: 8.5pt, fill: ink-soft)[#evt.date]
      #if evt.location != "" [
        #text(size: 8.5pt, fill: muted)[  ·  ]
        #text(size: 8.5pt, fill: ink-soft)[#evt.location]
      ]
      #if evt.address != "" [
        #linebreak()
        #text(size: 8pt, fill: muted)[#evt.address]
      ]
      #if evt.tags.len() > 0 [
        #v(3pt)
        #box[
          #evt.tags.map(chip).join(h(3pt))
        ]
      ]
      #if evt.url != "" or evt.route != "" [
        #v(3pt)
        #set text(size: 7.5pt)
        #if evt.url != "" [
          #text(fill: muted)[Event: ]
          #link(evt.url)[#evt.url]
        ]
        #if evt.url != "" and evt.route != "" [
          #linebreak()
        ]
        #if evt.route != "" [
          #text(fill: muted)[Route: ]
          #link(evt.route)[#evt.route]
        ]
      ]
    ],
    if evt.qr != "" {
      align(center)[
        #image(evt.qr, width: 18mm)
        #v(-4pt)
        #text(size: 6.5pt, fill: muted)[Scan for details]
      ]
    } else { [] },
  ),
)

// ---------- Document body ----------

#v(2pt)
#text(size: 18pt, weight: "bold", fill: ink)[Upcoming Rides]
#h(6pt)
#text(size: 10pt, fill: muted)[ #data.events.len() events ]
#v(2pt)
#text(size: 9pt, fill: muted)[
  Scan a QR code to view event details, or visit #link("https://ridewestside.org")[ridewestside.org].
]
#v(6pt)

#let sections = ("Next 90 Days", "Later This Year", "Beyond")
#for section in sections {
  let group = data.events.filter(e => e.section == section)
  if group.len() > 0 {
    block(above: 8pt, below: 4pt)[
      #text(size: 12pt, weight: "bold", fill: accent)[#section]
      #h(4pt)
      #text(size: 8.5pt, fill: muted)[(#group.len())]
      #v(-2pt)
      #line(length: 100%, stroke: 0.4pt + accent-line)
    ]
    for evt in group {
      event-card(evt)
    }
  }
}
`

func main() {
	if err := run(); err != nil {
		log.Fatal(err)
	}
}

func run() error {
	if _, err := exec.LookPath("typst"); err != nil {
		return fmt.Errorf("typst CLI not found in PATH: %w", err)
	}

	raw, err := os.ReadFile("content/events.md")
	if err != nil {
		return fmt.Errorf("reading events.md: %w", err)
	}

	parts := strings.SplitN(string(raw), "---", 3)
	if len(parts) < 3 {
		return fmt.Errorf("no YAML front matter in events.md")
	}

	var fm frontMatter
	if err := yaml.Unmarshal([]byte(parts[1]), &fm); err != nil {
		return fmt.Errorf("parsing events YAML: %w", err)
	}

	today := time.Now().Truncate(24 * time.Hour)
	type dated struct {
		e event
		t time.Time
	}
	var upcoming []dated
	for _, e := range fm.Events {
		if e.Date == "" {
			continue
		}
		t, err := time.Parse("January 2, 2006", e.Date)
		if err != nil {
			continue
		}
		if !t.Before(today) {
			upcoming = append(upcoming, dated{e, t})
		}
	}

	sort.SliceStable(upcoming, func(i, j int) bool {
		if upcoming[i].t.Equal(upcoming[j].t) {
			return upcoming[i].e.Title < upcoming[j].e.Title
		}
		return upcoming[i].t.Before(upcoming[j].t)
	})

	if len(upcoming) == 0 {
		fmt.Println("BuildPDF: no upcoming events found")
		return nil
	}

	tmpDir, err := os.MkdirTemp("", "buildpdf-")
	if err != nil {
		return fmt.Errorf("creating temp dir: %w", err)
	}
	defer os.RemoveAll(tmpDir)

	// Site-wide QR (header).
	sitePNG, err := qrcode.Encode("https://ridewestside.org", qrcode.Medium, 384)
	if err != nil {
		return fmt.Errorf("generating site QR: %w", err)
	}
	siteQRPath := filepath.Join(tmpDir, "site_qr.png")
	if err := os.WriteFile(siteQRPath, sitePNG, 0644); err != nil {
		return fmt.Errorf("writing site QR: %w", err)
	}

	// Per-URL QRs, deduped by URL.
	urlToQRFile := map[string]string{}
	for _, d := range upcoming {
		if d.e.URL == "" {
			continue
		}
		if _, ok := urlToQRFile[d.e.URL]; ok {
			continue
		}
		sum := sha1.Sum([]byte(d.e.URL))
		fname := "qr_" + hex.EncodeToString(sum[:8]) + ".png"
		png, err := qrcode.Encode(d.e.URL, qrcode.Medium, 320)
		if err != nil {
			continue
		}
		if err := os.WriteFile(filepath.Join(tmpDir, fname), png, 0644); err != nil {
			return fmt.Errorf("writing event QR: %w", err)
		}
		urlToQRFile[d.e.URL] = fname
	}

	tmpl := tmplData{
		Generated: time.Now().Format("January 2, 2006"),
		SiteURL:   "https://ridewestside.org",
		SiteQR:    "site_qr.png",
	}

	for _, d := range upcoming {
		days := int(d.t.Sub(today).Hours() / 24)
		section := "Next 90 Days"
		if days > 90 && d.t.Year() == today.Year() {
			section = "Later This Year"
		} else if d.t.Year() > today.Year() {
			section = "Beyond"
		}

		loc := d.e.Start
		if d.e.End != "" && d.e.End != d.e.Start {
			if loc == "" {
				loc = d.e.End
			} else {
				loc = loc + " → " + d.e.End
			}
		}

		te := tmplEvent{
			Title:    d.e.Title,
			Date:     d.t.Format("Monday, January 2, 2006"),
			Weekday:  d.t.Format("Mon"),
			Day:      d.t.Format("2"),
			Month:    d.t.Format("Jan"),
			URL:      d.e.URL,
			Route:    d.e.Route,
			Location: loc,
			Address:  d.e.StartAddress,
			Tags:     d.e.Tags,
			QR:       urlToQRFile[d.e.URL],
			Section:  section,
		}
		if te.Tags == nil {
			te.Tags = []string{}
		}
		tmpl.Events = append(tmpl.Events, te)
	}

	jsonBytes, err := json.MarshalIndent(tmpl, "", "  ")
	if err != nil {
		return fmt.Errorf("marshaling event data: %w", err)
	}
	if err := os.WriteFile(filepath.Join(tmpDir, "events.json"), jsonBytes, 0644); err != nil {
		return fmt.Errorf("writing events.json: %w", err)
	}

	typPath := filepath.Join(tmpDir, "events.typ")
	if err := os.WriteFile(typPath, []byte(typstTemplate), 0644); err != nil {
		return fmt.Errorf("writing events.typ: %w", err)
	}

	if err := os.MkdirAll("public", 0755); err != nil {
		return err
	}
	outPath := "public/events.pdf"
	absOut, err := filepath.Abs(outPath)
	if err != nil {
		return fmt.Errorf("resolving output path: %w", err)
	}

	cmd := exec.Command("typst", "compile", "--root", tmpDir, typPath, absOut)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("running typst: %w", err)
	}

	fmt.Printf("BuildPDF: wrote %d events to %s\n", len(upcoming), outPath)
	return nil
}
